version: "3"

services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    # uncomment below to persist mongodb
    #volumes:
    #  - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth